// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7K647QfmQ6ODpA7r2u83BKZ3aR9EG6w',
    appId: '1:435695420527:web:c81da72e000c6a85a1b99a',
    messagingSenderId: '435695420527',
    projectId: 'cocktail-flutterapp',
    authDomain: 'cocktail-flutterapp.firebaseapp.com',
    storageBucket: 'cocktail-flutterapp.appspot.com',
    measurementId: 'G-D9RMGXD3P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYOdK12-Yg8lVieVa256zglsCkmEardY',
    appId: '1:435695420527:android:63bb38ca330e13bda1b99a',
    messagingSenderId: '435695420527',
    projectId: 'cocktail-flutterapp',
    storageBucket: 'cocktail-flutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rraC5l3mxsnQZ7bTMZUV2MbGHdX3OSs',
    appId: '1:435695420527:ios:b7798fdfce40b579a1b99a',
    messagingSenderId: '435695420527',
    projectId: 'cocktail-flutterapp',
    storageBucket: 'cocktail-flutterapp.appspot.com',
    iosClientId: '435695420527-ffh41s53dg8uvek4bjl80tli6fa5sv5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppCocktail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rraC5l3mxsnQZ7bTMZUV2MbGHdX3OSs',
    appId: '1:435695420527:ios:b7798fdfce40b579a1b99a',
    messagingSenderId: '435695420527',
    projectId: 'cocktail-flutterapp',
    storageBucket: 'cocktail-flutterapp.appspot.com',
    iosClientId: '435695420527-ffh41s53dg8uvek4bjl80tli6fa5sv5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppCocktail',
  );
}
